// <auto-generated />
using System;
using Creditos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Creditos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Creditos.Models.Asesor", b =>
                {
                    b.Property<int>("IdAsesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsesor"), 1L, 1);

                    b.Property<string>("AsesorNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAsesor");

                    b.ToTable("Asesor");
                });

            modelBuilder.Entity("Creditos.Models.NotificacionAsesor", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsesor")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdAsesor");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("NotificacionAsesor");
                });

            modelBuilder.Entity("Creditos.Models.RespuestaCreditoFinanciera", b =>
                {
                    b.Property<int>("IdRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRespuesta"), 1L, 1);

                    b.Property<string>("Condiciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReproceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("JsonCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plazo")
                        .HasColumnType("int");

                    b.HasKey("IdRespuesta");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("RespuestaCreditoFinanciera");
                });

            modelBuilder.Entity("Creditos.Models.SolicitudCredito", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"), 1L, 1);

                    b.Property<int>("IdAsesor")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdAsesor");

                    b.ToTable("SolicitudCredito");
                });

            modelBuilder.Entity("Creditos.Models.NotificacionAsesor", b =>
                {
                    b.HasOne("Creditos.Models.Asesor", "Asesor")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdAsesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Creditos.Models.SolicitudCredito", "Solicitud")
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asesor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Creditos.Models.RespuestaCreditoFinanciera", b =>
                {
                    b.HasOne("Creditos.Models.SolicitudCredito", "SolicitudCredito")
                        .WithMany("RespuestasCreditos")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SolicitudCredito");
                });

            modelBuilder.Entity("Creditos.Models.SolicitudCredito", b =>
                {
                    b.HasOne("Creditos.Models.Asesor", "Asesor")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdAsesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asesor");
                });

            modelBuilder.Entity("Creditos.Models.Asesor", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Creditos.Models.SolicitudCredito", b =>
                {
                    b.Navigation("RespuestasCreditos");
                });
#pragma warning restore 612, 618
        }
    }
}
